### ISSUE TITLE
Add development mode

### ISSUE THREAD

**Issue by ABODFTW** [girder/django-s3-file-field#155]
It would be nice to have a minimal way of configuring the tool to work on dev the same as in the production

**Comment by brianhelba** [comment]
@ABODFTW I'm not exactly clear on what you mean.

If you're referring to tools to develop `django-s3-file-field` itself, we have [the `example/` project](https://github.com/girder/django-s3-file-field/tree/master/example), which was recently updated and documented.

If you're referring to downstream use in a Django project, it's probably outside the scope of `django-s3-file-field` itself to behave differently in a "dev" vs "prod" type environment. Rather, you probably want your configuration of a Django Storage to be different in each, which is outside the responsibility of `django-s3-file-field`.

You might want to check out [the Storage settings in `django-composed-configuration`](https://github.com/girder/django-composed-configuration/blob/master/composed_configuration/_storage.py) for a good set of defaults. Also, see [`cookiecutter-django-girder`](https://github.com/girder/cookiecutter-django-girder) for a project cookiecutter which provides a zero-configuration setup using MinIO for Storage in development.

**Comment by ABODFTW** [comment]
My bad, I was analyzing multiple s3 libraries for Django, and I meant to add this to the s3direct library but instead, I submitted it here, thanks for the info tho.
