### ISSUE TITLE
Support downloading inline or attachment content disposition

### ISSUE THREAD

**Issue by zachmullen** [girder/django-s3-file-field#197]
See https://github.com/girder/girder/blob/master/girder/utility/s3_assetstore_adapter.py#L389 for reference on how to achieve this with boto3.

**Comment by zachmullen** [comment]
For setting keys on the object related to content type and disposition, see https://github.com/girder/girder/blob/master/girder/utility/s3_assetstore_adapter.py#L151-L155

**Comment by brianhelba** [comment]
This is out of scope of S3FileField, since it involves downloading, which S3FF does not participate in.

Ensuring that content type and filename fields are corrected sent to the Storage layer (and ultimately S3), may be in scope, so I'll open a new issue for that.
