### ISSUE TITLE
Investigate extending the system checks framework

### ISSUE THREAD

**Issue by danlamanna** [girder/django-s3-file-field#20]
I think this could provide assistance in 1) configuring the backing store correctly and 2) testing accessibility to the backing store.

**Comment by sgratzl** [comment]
see https://docs.djangoproject.com/en/2.2/ref/checks/

**Comment by danlamanna** [comment]
Fixed in https://github.com/girder/django-s3-file-field/commit/9e141bb01e6111614d8a1faabf0729d124eeb492.
